package fflow

import (
	"fmt"
	"strconv"
	"strings"
)

type writeStage interface {
	// VideoCodec define o codec de vídeo do output (-c:v).
	//
	// VideoCodec sets the output video codec (-c:v).
	VideoCodec(codec string) writeStage

	// AudioCodec define o codec de áudio do output (-c:a).
	//
	// AudioCodec sets the output audio codec (-c:a).
	AudioCodec(codec string) writeStage

	// SubtitleCodec define o codec de legenda do output (-c:s).
	//
	// SubtitleCodec sets the output subtitle codec (-c:s).
	SubtitleCodec(codec string) writeStage

	// CopyVideo copia o stream de vídeo sem recodificar (-c:v copy).
	//
	// CopyVideo copies the video stream without re-encoding (-c:v copy).
	CopyVideo() writeStage

	// CopyAudio copia o stream de áudio sem recodificar (-c:a copy).
	//
	// CopyAudio copies the audio stream without re-encoding (-c:a copy).
	CopyAudio() writeStage

	// CodecFor define o codec de um stream específico do output (-c:<stream>:<index>).
	//
	// CodecFor sets the codec for a specific output stream (-c:<stream>:<index>).
	CodecFor(stream StreamType, index int, codec string) writeStage

	// CRF define o fator de qualidade constante para encoders de vídeo.
	//
	// CRF sets the constant quality factor for video encoders.
	CRF(value int) writeStage

	// Map adiciona a opção -map ao comando FFmpeg.
	//
	// O valor informado é usado exatamente como fornecido.
	//
	// Exemplos:
	//   Map("[out]") // filter_complex
	//   Map("0:v")   // vídeo do input 0
	//   Map("0:a")   // áudio do input 0
	//
	// Map adds the -map option to the FFmpeg command.
	//
	// The provided value is used verbatim.
	Map(selector string) writeStage

	// Raw adiciona um ou mais argumentos brutos ao comando FFmpeg.
	// Útil para opções ainda não abstraídas e para passar flags com seus valores.
	// Exemplo: `.Raw("-b:a", "192k")`
	//
	// Raw adds one or more raw arguments to the FFmpeg command.
	// Useful for unabstracted options and for passing flags with their values.
	// Example: `.Raw("-b:a", "192k")`
	Raw(values ...string) writeStage

	// Preset adiciona a flag -preset ao encoder de vídeo na saída.
	// Controla o trade-off entre velocidade de codificação e eficiência de compressão.
	//
	// Preset adds the -preset flag to the video encoder at the output stage.
	// It controls the trade-off between encoding speed and compression efficiency.
	Preset(value string) writeStage

	// Output define o arquivo de saída.
	//
	// Output sets the output file path.
	Output(path string) writeStage

	// Build monta o comando FFmpeg completo, incluindo o binário "ffmpeg"
	// e todos os argumentos gerados, respeitando a ordem semântica.
	//
	// Build assembles the full FFmpeg command, including the "ffmpeg" binary
	// and all generated arguments, respecting semantic order.
	Build() string

	// Args retorna apenas os argumentos gerados pelo builder,
	// sem incluir o binário "ffmpeg".
	//
	// Args returns only the arguments generated by the builder,
	// excluding the "ffmpeg" binary.
	Args() []string

	// String retorna os argumentos do FFmpeg como uma única string,
	// sem incluir o binário "ffmpeg".
	//
	// String returns the FFmpeg arguments as a single string,
	// excluding the "ffmpeg" binary.
	String() string

	// Command transiciona para o commandStage.
	//
	// Command transitions to commandStage.
	Command() commandStage
}

type writeCtx struct{ b *ffmpegBuilder }

func (c *writeCtx) VideoCodec(codec string) writeStage {
	c.b.write = append(c.b.write, "-c:v", codec)
	return c
}

func (c *writeCtx) AudioCodec(codec string) writeStage {
	c.b.write = append(c.b.write, "-c:a", codec)
	return c
}

func (c *writeCtx) SubtitleCodec(codec string) writeStage {
	c.b.write = append(c.b.write, "-c:s", codec)
	return c
}

func (c *writeCtx) CodecFor(stream StreamType, index int, codec string) writeStage {
	c.b.write = append(c.b.write, fmt.Sprintf("-c:%s:%d", stream, index), codec)
	return c
}

func (c *writeCtx) CopyVideo() writeStage {
	c.b.write = append(c.b.write, "-c:v", "copy")
	return c
}

func (c *writeCtx) CopyAudio() writeStage {
	c.b.write = append(c.b.write, "-c:a", "copy")
	return c
}

func (c *writeCtx) CRF(value int) writeStage {
	c.b.write = append(c.b.write, "-crf", strconv.Itoa(value))
	return c
}

func (c *writeCtx) Preset(value string) writeStage {
	c.b.write = append(c.b.write, "-preset", value)
	return c
}

func (c *writeCtx) Map(selector string) writeStage {
	c.b.write = append(c.b.write, "-map", selector)
	return c
}

func (c *writeCtx) Raw(values ...string) writeStage {
	c.b.write = append(c.b.write, values...)
	return c
}

func (c *writeCtx) Output(path string) writeStage {
	c.b.output = path
	return c
}

func (c *writeCtx) Args() []string {
	var args []string

	args = append(args, c.b.beforeRead...)
	args = append(args, c.b.read...)
	if len(c.b.filters) > 0 {
		pipeline := Pipeline{Nodes: c.b.filters}
		if pipeline.NeedsComplex() {
			args = append(args, "-filter_complex", pipeline.String())
		} else {
			args = append(args, c.b.simpleFilterFlag, pipeline.String())
		}
	}
	args = append(args, c.b.write...)
	args = append(args, c.b.output)
	return args
}

func (c *writeCtx) String() string {
	return strings.Join(c.Args(), " ")
}

func (c *writeCtx) Build() string {
	args := []string{"ffmpeg"}
	args = append(args, c.Args()...)
	return strings.Join(args, " ")
}

func (c *writeCtx) Command() commandStage {
	return &commandCtx{c.b}
}
